function results = target_sorbent_circulation( ...
    N_ads, N_des, ...
    n_g_feed, yCO2_feed, ...
    n_steam_in, ...
    capture_target, ...
    m_s_bracket, ...
    T_ads, T_des, P_bar, ...
    Isotherm, ...
    beta_lean_guess, ...
    relaxation, tol_beta, max_iter)
% target_sorbent_circulation
% Determines the sorbent circulation rate required to achieve
% a specified CO2 capture target for a fixed stripping steam flow.
%
% Outer solution:
%   vary m_s
%       -> converge closed TSA beta loop
%       -> calculate capture fraction
%       -> find m_s where capture_fraction = capture_target
%
% The validated adsorber, desorber, and coupled-loop formulations
% are not modified.

    %% =========================
    % CHECK CIRCULATION BRACKET
    % ==========================

    if numel(m_s_bracket) ~= 2
        error('m_s_bracket must contain exactly two values.');
    end

    m_s_low = m_s_bracket(1);
    m_s_high = m_s_bracket(2);

    if m_s_low <= 0 || m_s_high <= m_s_low
        error('Invalid sorbent circulation bracket.');
    end

    %% =========================
    % DEFINE CAPTURE-TARGET OBJECTIVE
    % ==========================

    capture_objective = @(m_s) coupled_capture_error( ...
        m_s, ...
        N_ads, N_des, ...
        n_g_feed, yCO2_feed, ...
        n_steam_in, ...
        capture_target, ...
        T_ads, T_des, P_bar, ...
        Isotherm, ...
        beta_lean_guess, ...
        relaxation, tol_beta, max_iter);

    %% =========================
    % VERIFY ROOT BRACKET
    % ==========================

    error_low = capture_objective(m_s_low);
    error_high = capture_objective(m_s_high);

    fprintf('\n===== SORBENT CIRCULATION TARGETING =====\n');
    fprintf('Capture target                  = %.8f %%\n', ...
        100 * capture_target);
    fprintf('Lower m_s bracket               = %.8f kg/s\n', ...
        m_s_low);
    fprintf('Lower capture error             = %+.8e\n', ...
        error_low);
    fprintf('Upper m_s bracket               = %.8f kg/s\n', ...
        m_s_high);
    fprintf('Upper capture error             = %+.8e\n', ...
        error_high);

    if error_low * error_high > 0
        error(['Sorbent circulation bracket does not contain the ', ...
               'capture target. Capture errors have the same sign.']);
    end

    %% =========================
    % TARGET SORBENT CIRCULATION
    % ==========================

    fzero_options = optimset( ...
        'Display', 'iter', ...
        'TolX', 1e-8);

    m_s_target = fzero( ...
        capture_objective, ...
        [m_s_low, m_s_high], ...
        fzero_options);

    %% =========================
    % FINAL COUPLED TSA SOLUTION
    % ==========================

    coupled_results = solve_coupled_TSA_fixed_ms( ...
        N_ads, N_des, ...
        n_g_feed, yCO2_feed, ...
        m_s_target, ...
        n_steam_in, ...
        T_ads, T_des, P_bar, ...
        Isotherm, ...
        beta_lean_guess, ...
        relaxation, tol_beta, max_iter);

    %% =========================
    % STORE RESULTS
    % ==========================

    results = coupled_results;

    results.m_s_target = m_s_target;
    results.capture_target = capture_target;

    results.capture_error = ...
        coupled_results.capture_fraction - capture_target;

end


function capture_error = coupled_capture_error( ...
    m_s, ...
    N_ads, N_des, ...
    n_g_feed, yCO2_feed, ...
    n_steam_in, ...
    capture_target, ...
    T_ads, T_des, P_bar, ...
    Isotherm, ...
    beta_lean_guess, ...
    relaxation, tol_beta, max_iter)
% coupled_capture_error
% Evaluates the capture-target residual for one trial sorbent flow.

    trial_results = solve_coupled_TSA_fixed_ms( ...
        N_ads, N_des, ...
        n_g_feed, yCO2_feed, ...
        m_s, ...
        n_steam_in, ...
        T_ads, T_des, P_bar, ...
        Isotherm, ...
        beta_lean_guess, ...
        relaxation, tol_beta, max_iter);

    capture_error = ...
        trial_results.capture_fraction - capture_target;

end